# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 069b79583be95720757d37dac214972803fa53826dce84d3c65d63e40a5c347c45fb1104a97270fd2396167151b9732cb5d005108af761986cad39932f5b7a46

test:
  secret_key_base: 15ca1e11c7644a438ae384d459d8cffb6e70091b140589ca868c7297605f95a28ce4437a78f7994c39249e5f88e95a1286fbb7e44e87736f0beea11a99547132

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
